project:
  type: book

book:
  title: "It's not just code: managing an open source project"
  author: "Tracy Teal"
  date: "2/25/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - project-goals.qmd
    - project-setup.qmd
    - documentation.qmd
    - governance.qmd
    - community-interactions.qmd
    - project-management.qmd
    - maintenance.qmd
    - funding.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

