# Funding

Is this maybe the topic you've been waiting for? Well, here's the good news, all that you've done to set up your project has put you on a good path for attracting funding. Yes, as with everything else, there's still work to do, and skills you need, but one key is having a project structure that shows that you as a project have goals, the capacity to make decisions and a structure that supports the project and community.

Alas, funding won't come to you just because you're an important project. Queue xkxd comic of the internet infrastructure resting on a small stone maintained by one person in Nebraska. Now, here I am describing the world as it seems to be, rather than the world as I wish it was. We can have a whole different conversation about that, but let's start where we are. 

Here of course, we again start with questions. This will help you decide where to look for funding and how to frame asking for it. 

* What would funding allow you to do that you can't do now?
* How would you make decisions about how to use the month, should you get it?
* Is there a business model (this is a whole deal of course) that can be made around the project?
* How much money would make a difference? 
* How will people give you money? 
* Do you have a bank account for the project, where will you get and store your money? (please not under a mattress)
* How to get funding in different range areas - donations good for small amounts, grants for bigger, etc. 
* Academic context 

When you're asking for funding, you can point to the information you have around how decisions are made, to let them know. Then you can say if I have X dollars, I would have more maintenance capacity, so I could make decisions for the project differently. Or if we had Y dollars, I could expand the scope of the project to do this new thing. 
